general.import = [
  # uncomment the flavour you want below:
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
  #	"~/.config/alacritty/gruvbox_dark.toml"
  	"~/.config/alacritty/sonokai.toml"
]


[window]

opacity = 1

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" #"Light"  

[font]
# linux list fonts cmd= fc-list
normal = { family = "Iosevka Custom", style = "Regular" }
bold = { family = "Iosevka Custom", style = "Bold" }
italic = { family = "Iosevka Custom", style = "Italic" }
bold_italic = { family = "Iosevka Custom", style = "Bold Italic" }

size = 15.0
